#pragma once

#include <Windows.h>

enum class KeyCode {
    // 기본 키
    LButton = VK_LBUTTON,
    RButton = VK_RBUTTON,
    Cancel = VK_CANCEL,
    MButton = VK_MBUTTON,
    XButton1 = VK_XBUTTON1,
    XButton2 = VK_XBUTTON2,

    // 기능 키
    Backspace = VK_BACK,
    Tab = VK_TAB,
    Clear = VK_CLEAR,
    Enter = VK_RETURN,
    Shift = VK_SHIFT,
    Control = VK_CONTROL,
    Alt = VK_MENU,
    Pause = VK_PAUSE,
    CapsLock = VK_CAPITAL,
    ESC = VK_ESCAPE,
    Space = VK_SPACE,
    PageUp = VK_PRIOR,
    PageDown = VK_NEXT,
    End = VK_END,
    Home = VK_HOME,
    LeftArrow = VK_LEFT,
    UpArrow = VK_UP,
    RightArrow = VK_RIGHT,
    DownArrow = VK_DOWN,
    Select = VK_SELECT,
    Print = VK_PRINT,
    Execute = VK_EXECUTE,
    PrintScreen = VK_SNAPSHOT,
    Insert = VK_INSERT,
    Delete = VK_DELETE,
    Help = VK_HELP,

    // 0-9 숫자 키
    Num0 = VK_NUMPAD0,
    Num1 = VK_NUMPAD1,
    Num2 = VK_NUMPAD2,
    Num3 = VK_NUMPAD3,
    Num4 = VK_NUMPAD4,
    Num5 = VK_NUMPAD5,
    Num6 = VK_NUMPAD6,
    Num7 = VK_NUMPAD7,
    Num8 = VK_NUMPAD8,
    Num9 = VK_NUMPAD9,

    // A-Z 문자 키

    A = 0x41,
    B = 0x42,
    C = 0x43,
    D = 0x44,
    E = 0x45,
    F = 0x46,
    G = 0x47,
    H = 0x48,
    I = 0x49,
    J = 0x4A,
    K = 0x4B,
    L = 0x4C,
    M = 0x4D,
    N = 0x4E,
    O = 0x4F,
    P = 0x50,
    Q = 0x51,
    R = 0x52,
    S = 0x53,
    T = 0x54,
    U = 0x55,
    V = 0x56,
    W = 0x57,
    X = 0x58,
    Y = 0x59,
    Z = 0x5A,

    // 기타 특수 키
    LeftWindows = VK_LWIN,
    RightWindows = VK_RWIN,
    Apps = VK_APPS,
    Sleep = VK_SLEEP,
    NumMultiply = VK_MULTIPLY,
    NumAdd = VK_ADD,
    NumSeparator = VK_SEPARATOR,
    NumSubtract = VK_SUBTRACT,
    NumDecimal = VK_DECIMAL,
    NumDivide = VK_DIVIDE,
    F1 = VK_F1,
    F2 = VK_F2,
    F3 = VK_F3,
    F4 = VK_F4,
    F5 = VK_F5,
    F6 = VK_F6,
    F7 = VK_F7,
    F8 = VK_F8,
    F9 = VK_F9,
    F10 = VK_F10,
    F11 = VK_F11,
    F12 = VK_F12,
    F13 = VK_F13,
    F14 = VK_F14,
    F15 = VK_F15,
    F16 = VK_F16,
    F17 = VK_F17,
    F18 = VK_F18,
    F19 = VK_F19,
    F20 = VK_F20,
    F21 = VK_F21,
    F22 = VK_F22,
    F23 = VK_F23,
    F24 = VK_F24,
    NumLock = VK_NUMLOCK,
    ScrollLock = VK_SCROLL,
    LeftShift = VK_LSHIFT,
    RightShift = VK_RSHIFT,
    LeftControl = VK_LCONTROL,
    RightControl = VK_RCONTROL,
    LeftAlt = VK_LMENU,
    RightAlt = VK_RMENU,

    // 미지정 특수 키

    BrowserBack = VK_BROWSER_BACK,
    BrowserForward = VK_BROWSER_FORWARD,
    BrowserRefresh = VK_BROWSER_REFRESH,
    BrowserStop = VK_BROWSER_STOP,
    BrowserSearch = VK_BROWSER_SEARCH,
    BrowserFavorites = VK_BROWSER_FAVORITES,
    BrowserHome = VK_BROWSER_HOME,
    VolumeMute = VK_VOLUME_MUTE,
    VolumeDown = VK_VOLUME_DOWN,
    VolumeUp = VK_VOLUME_UP,
    MediaNextTrack = VK_MEDIA_NEXT_TRACK,
    MediaPrevTrack = VK_MEDIA_PREV_TRACK,
    MediaStop = VK_MEDIA_STOP,
    MediaPlayPause = VK_MEDIA_PLAY_PAUSE,
    LaunchMail = VK_LAUNCH_MAIL,
    LaunchMediaSelect = VK_LAUNCH_MEDIA_SELECT,
    LaunchApp1 = VK_LAUNCH_APP1,
    LaunchApp2 = VK_LAUNCH_APP2
};


enum class MouseCode {
    LeftClick = 0,
    RightClick,
    WheelClick,
    WheelUp,
    WheelDown,
};